### ISSUE TITLE
Remove moment dependency

### ISSUE THREAD

**Issue by vinceau** [project-slippi/slippi-js#101]
We currently only use the `moment` library for two things:
1. calling `moment().toISOString()`
2. formatting the initial filename for SLP files

We do not need to import the entirety of `moment` just to use this functionality. We can simply use `(new Date()).toISOString()` and `import { format } from 'date-fns'` to format the date keeping in mind that the [format string is 🚨**different**🚨 to `moment`](https://date-fns.org/v2.28.0/docs/format).

**Comment by shrianshChari** [comment]
#103
