### ISSUE TITLE
exporting characterUtils does not work

### ISSUE THREAD

**Issue by zmoney20** [project-slippi/slippi-js#139]
I am trying to use `getCharacterInfo` from the characterUtils. By default, intellisense is telling me to import with this:
```
import { getCharacterInfo } from "@slippi/slippi-js/dist/melee/characterUtils";
```

But then I run into this error:
```
Error: Package subpath './dist/melee/characterUtils' is not defined by "exports" in .../node_modules/@slippi/slippi-js/package.json
```

I've also tried:
```
import { getCharacterInfo } from "@slippi/slippi-js";
```
but get:
```
TSError: ⨯ Unable to compile TypeScript:
index.ts:5:10 - error TS2305: Module '"@slippi/slippi-js"' has no exported member 'getCharacterInfo'.
```
I fixed this in a local branch with the following:
![image](https://github.com/user-attachments/assets/a19a5079-3cd0-47b6-a349-c6a5a1f782a6)

Which now allows me to import with this:
```
import { getCharacterInfo } from "@slippi/slippi-js";
```

Which I believe should be the preferred way to import this util function.

If there is another way I should be importing this, please let me know. Thank you!

**Comment by NikhilNarayana** [comment]
you can import it with this line

`import { characters } from "@slippi/slippi-js";`

https://github.com/project-slippi/slippi-launcher/blob/4159a19dd20f9e0e8649a62a0522920709f93de1/src/renderer/lib/utils.ts#L1
