### ISSUE TITLE
Why are the stageIds missing numbers?

### ISSUE THREAD

**Issue by PMcca** [project-slippi/slippi-js#70]
I've noticed the stageIds are missing numbers, visible in the enums too (see `melee/types.js`). The numbers missing are 0, 1 and 21 weirdly. 

What is the reason for this? What prevented/prevents the stageIds from being enumerable and in complete sequence?

**Comment by yashichidsf** [comment]
https://docs.google.com/spreadsheets/d/1JX2w-r2fuvWuNgGb6D3Cs4wHQKLFegZe2jhbBuIhCG8/preview#gid=20 they are not valid, normally accessible stages. Dummy (0), TEST (1), and Akaneia (21)

**Comment by NikhilNarayana** [comment]
Those are from the game and you can see a full list of stages here: https://docs.google.com/spreadsheets/d/152A_UrA996o5VXveCkfJVPVuVBHP-90HxdkU72m0Ioc/edit#gid=20

Those specific ones are just not needed by us so we don't include them.

For future questions that aren't slippi-js bugs or such, please use our discord.

**Comment by ckeatsps** [comment]
slippi-js uses the internal stages IDs of the game, and those three numbers aren't valid stages.

See docs.google.com/spreadsheets/d/1JX2w-r2fuvWuNgGb6D3Cs4wHQKLFegZe2jhbBuIhCG8/preview#gid=20

**Comment by PMcca** [comment]
Thanks, v helpful to know
